USE [master]
GO
/****** Object:  Database [IDAAI]    Script Date: 27/11/2022 18:47:01 ******/
CREATE DATABASE [IDAAI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IDAAI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IDAAI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IDAAI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IDAAI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [IDAAI] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IDAAI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IDAAI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IDAAI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IDAAI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IDAAI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IDAAI] SET ARITHABORT OFF 
GO
ALTER DATABASE [IDAAI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IDAAI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IDAAI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IDAAI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IDAAI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IDAAI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IDAAI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IDAAI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IDAAI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IDAAI] SET  ENABLE_BROKER 
GO
ALTER DATABASE [IDAAI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IDAAI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IDAAI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IDAAI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IDAAI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IDAAI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IDAAI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IDAAI] SET RECOVERY FULL 
GO
ALTER DATABASE [IDAAI] SET  MULTI_USER 
GO
ALTER DATABASE [IDAAI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IDAAI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IDAAI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IDAAI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IDAAI] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IDAAI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'IDAAI', N'ON'
GO
ALTER DATABASE [IDAAI] SET QUERY_STORE = OFF
GO
USE [IDAAI]
GO
/****** Object:  Table [dbo].[Carreras]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carreras](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Carreras] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EstadoAsistencia]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EstadoAsistencia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [varchar](25) NOT NULL,
 CONSTRAINT [PK_EstadoAsistencia] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EstadoDevolucion]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EstadoDevolucion](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [varchar](25) NOT NULL,
 CONSTRAINT [PK_EstadoDevolucion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EstadoItem]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EstadoItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [varchar](25) NOT NULL,
 CONSTRAINT [PK_EstadoItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiantes]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [varchar](100) NOT NULL,
	[Apellidos] [varchar](100) NOT NULL,
	[Matricula] [varchar](10) NOT NULL,
	[Email] [varchar](50) NULL,
	[Direccion] [varchar](100) NULL,
	[CarreraId] [int] NULL,
	[ModuloId] [int] NOT NULL,
 CONSTRAINT [PK_Estudiantes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Inventario]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](25) NOT NULL,
	[Descripcion] [varchar](50) NULL,
	[CantidadDisponible] [int] NULL,
	[CantidadTotal] [int] NULL,
	[ModuloId] [int] NOT NULL,
 CONSTRAINT [PK_Inventario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Items]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Items](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Rfid] [varchar](100) NOT NULL,
	[EstadoItemId] [int] NULL,
	[InventarioId] [int] NULL,
 CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Modulos]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Modulos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Descripcion] [varchar](100) NULL,
 CONSTRAINT [PK_Modulos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegistroAsistencia]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegistroAsistencia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[EstudianteId] [int] NOT NULL,
	[EstadoAsistenciaId] [int] NULL,
 CONSTRAINT [PK_RegistroAsistencia] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegistroPrestamoItem]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegistroPrestamoItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FechaPrestado] [datetime] NOT NULL,
	[FechaDevuelto] [datetime] NULL,
	[EstudianteId] [int] NOT NULL,
	[ItemId] [int] NOT NULL,
	[EstadoDevolucionId] [int] NOT NULL,
 CONSTRAINT [PK_RegistroPrestamoItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 27/11/2022 18:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [varchar](25) NOT NULL,
	[Password] [varchar](200) NOT NULL,
	[ModuloId] [int] NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Carreras] ON 
GO
INSERT [dbo].[Carreras] ([Id], [Nombre]) VALUES (1, N'Ingeniería en Telemática')
GO
SET IDENTITY_INSERT [dbo].[Carreras] OFF
GO
SET IDENTITY_INSERT [dbo].[EstadoAsistencia] ON 
GO
INSERT [dbo].[EstadoAsistencia] ([Id], [Estado]) VALUES (1, N'Asistencia')
GO
INSERT [dbo].[EstadoAsistencia] ([Id], [Estado]) VALUES (2, N'Falta')
GO
SET IDENTITY_INSERT [dbo].[EstadoAsistencia] OFF
GO
SET IDENTITY_INSERT [dbo].[EstadoDevolucion] ON 
GO
INSERT [dbo].[EstadoDevolucion] ([Id], [Estado]) VALUES (1, N'Devuelto')
GO
INSERT [dbo].[EstadoDevolucion] ([Id], [Estado]) VALUES (2, N'Prestado')
GO
INSERT [dbo].[EstadoDevolucion] ([Id], [Estado]) VALUES (3, N'Atrasado')
GO
SET IDENTITY_INSERT [dbo].[EstadoDevolucion] OFF
GO
SET IDENTITY_INSERT [dbo].[EstadoItem] ON 
GO
INSERT [dbo].[EstadoItem] ([Id], [Estado]) VALUES (1, N'Disponible')
GO
INSERT [dbo].[EstadoItem] ([Id], [Estado]) VALUES (2, N'No Disponible')
GO
SET IDENTITY_INSERT [dbo].[EstadoItem] OFF
GO
SET IDENTITY_INSERT [dbo].[Modulos] ON 
GO
INSERT [dbo].[Modulos] ([Id], [Nombre], [Descripcion]) VALUES (1, N'LST', N'Laboratorio de Sistemas Telemáticos')
GO
SET IDENTITY_INSERT [dbo].[Modulos] OFF
GO
SET IDENTITY_INSERT [dbo].[Usuarios] ON 
GO
INSERT [dbo].[Usuarios] ([Id], [Usuario], [Password], [ModuloId]) VALUES (1, N'admin', N'admin', 1)
GO
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO
ALTER TABLE [dbo].[Estudiantes]  WITH CHECK ADD  CONSTRAINT [FK__Estudiant__Carre__33D4B598] FOREIGN KEY([CarreraId])
REFERENCES [dbo].[Carreras] ([Id])
GO
ALTER TABLE [dbo].[Estudiantes] CHECK CONSTRAINT [FK__Estudiant__Carre__33D4B598]
GO
ALTER TABLE [dbo].[Estudiantes]  WITH CHECK ADD  CONSTRAINT [FK__Estudiant__Modul__35BCFE0A] FOREIGN KEY([ModuloId])
REFERENCES [dbo].[Modulos] ([Id])
GO
ALTER TABLE [dbo].[Estudiantes] CHECK CONSTRAINT [FK__Estudiant__Modul__35BCFE0A]
GO
ALTER TABLE [dbo].[Inventario]  WITH CHECK ADD FOREIGN KEY([ModuloId])
REFERENCES [dbo].[Modulos] ([Id])
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD FOREIGN KEY([EstadoItemId])
REFERENCES [dbo].[EstadoItem] ([Id])
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD FOREIGN KEY([InventarioId])
REFERENCES [dbo].[Inventario] ([Id])
GO
ALTER TABLE [dbo].[RegistroAsistencia]  WITH CHECK ADD FOREIGN KEY([EstadoAsistenciaId])
REFERENCES [dbo].[EstadoAsistencia] ([Id])
GO
ALTER TABLE [dbo].[RegistroAsistencia]  WITH CHECK ADD FOREIGN KEY([EstudianteId])
REFERENCES [dbo].[Estudiantes] ([Id])
GO
ALTER TABLE [dbo].[RegistroPrestamoItem]  WITH CHECK ADD FOREIGN KEY([EstadoDevolucionId])
REFERENCES [dbo].[EstadoDevolucion] ([Id])
GO
ALTER TABLE [dbo].[RegistroPrestamoItem]  WITH CHECK ADD FOREIGN KEY([EstudianteId])
REFERENCES [dbo].[Estudiantes] ([Id])
GO
ALTER TABLE [dbo].[RegistroPrestamoItem]  WITH CHECK ADD FOREIGN KEY([ItemId])
REFERENCES [dbo].[Items] ([Id])
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD FOREIGN KEY([ModuloId])
REFERENCES [dbo].[Modulos] ([Id])
GO
USE [master]
GO
ALTER DATABASE [IDAAI] SET  READ_WRITE 
GO
